### ISSUE TITLE
Image on Docker Hub

### ISSUE THREAD

**Issue by aheinze** [aheinze/cockpit-docker#1]
Hi @andrefreitas , first let me thank you for your contribution! For the next step you need to publish on Docker hub, right? May I send you the login data and you take care of it?

Again, thank you for your time and work!

**Comment by andrefreitas** [comment]
Hi @aheinze, ou are welcome, we are probably going to use Cockpit in the place I work so this is a way of giving back :)

You are right, we need to publish to Dockerhub and for security reasons I would prefer to not have your credentials. I already prepared most of the stuff so you just need to do the following:

- [ ] Create an account in [Dockerhub](https://hub.docker.com/) with the username `aheinze`
- [ ] Create a repository in [Dockerhub](https://hub.docker.com/)  named `cockpit` with a short description and the full description is the raw content of [this Markdown file](https://github.com/aheinze/cockpit-docker/blob/master/DOCKERHUB.md).
- [ ] Setup a Travis Job with this repository.
- [ ] Create in Travis the environment variables: `DOCKERHUB_REPOSITORY=cockpit` and `DOCKERHUB_PASSWORD=[PROTECTED_PASSWORD]`

When this is done, I will trigger the build in Travis and check if everything is okay.

Thanks,
AF

**Comment by aheinze** [comment]
Hi,

I followed your steps and setup everything so far. Still curios about DOCKERHUB_REPOSITORY=cockpit , shouldn't it be DOCKERHUB_REPOSITORY=aheinze/cockpit ?

**Comment by andrefreitas** [comment]
Hi,
Well, I am using the repository without the name part, to be in another variable:

    docker push $(DOCKERHUB_USERNAME)/$(DOCKERHUB_REPOSITORY):$(DOCKER_TAG)

The username part is actually called the namespace, that can be another registry besides the one from Dockerhub.

**Comment by aheinze** [comment]
Alright, thanks for the clarification!

Another point:

Is it also possible to checkout cockpit next (https://github.com/aheinze/cockpit/tree/next)  via a make  parameter?

**Comment by andrefreitas** [comment]
Hi,
Yes, I will make a tag just for the cockpit next. I forgot to ask your dockerhub email that is also necessary. Can you provide?

**Comment by aheinze** [comment]
thanks and sure ... artur@agentejo.com

**Comment by andrefreitas** [comment]
Hi,
Just added the build of cockpit:next too. Everything is working now :) I have updated the DOCKERHUB.md, please update it in Dockerhub.

It would be good to trigger the travis build from the cockpit repository but seems that Travis doesn't allows it. No problem, each time there is a new version we update the DOCKERHUB.md with that tag, commit and that will trigger the build.

**Comment by aheinze** [comment]
Done! Thanks for taking to implement this!
