### ISSUE TITLE
Configure cockpit from environment variables

### ISSUE THREAD

**Issue by andrefreitas** [aheinze/cockpit-docker#2]
Hi @aheinze,
I am working in supporting the configuration of the container with environment variables (it's a common approach in Docker):

```php
<?php


$configs = [];

if (!empty(getenv('COCKPIT_SESSION_NAME'))){
  $configs['session.name'] = getenv('COCKPIT_SESSION_NAME');
}

if (!empty(getenv('COCKPIT_SALT'))){
  $configs['sec-key'] = getenv('COCKPIT_SALT');
}

if (!empty(getenv('COCKPIT_I18N'))){
  $configs['i18n'] = getenv('COCKPIT_I18N');
}

if (!empty(getenv('COCKPIT_DATABASE_SERVER'))){
  $configs['database'] = [
    "server"  => getenv('COCKPIT_DATABASE_SERVER'),
    "options" => ["db" => getenv('COCKPIT_DATABASE_NAME')]
  ];
}

if (!empty(getenv('COCKPIT_MAILER_FROM'))){
  $configs['mailer'] = [
      "from"      => getenv('COCKPIT_MAILER_FROM'),
      "transport" => getenv('COCKPIT_MAILER_TRANSPORT'),
      "host"      => getenv('COCKPIT_MAILER_HOST'),
      "user"      => getenv('COCKPIT_MAILER_USER'),
      "password"  => getenv('COCKPIT_MAILER_PASSWORD'),
      "port"      => getenv('COCKPIT_MAILER_PORT'),
      "auth"      => getenv('COCKPIT_MAILER_AUTH'),
      "encryption"=> getenv('COCKPIT_MAILER_ENCRYPTION')
  ];
}
return $configs;
```
I am testing cockpit, latest version,  and I am having an error with the MongoDB client. 

```
Fatal error: Uncaught Error: Class 'MongoClient' not found 
```

This is due the fact you are using an old Driver of Mongo: http://php.net/manual/en/class.mongoclient.php

- Do you have any plans in migrating to the new driver? 
- The `next` branch of Cockpit is reading the configs from custom/config.php? (isn't working with that branch)

**Comment by aheinze** [comment]
Hi,

Cockpit Next used to load  ```config/config.yaml```  but can now also load  ```config/config.php``` if the file exists. I have to look into the new mongo driver thing. didn't know anything about it until now.

**Comment by andrefreitas** [comment]
Hi Artur,

> Cockpit Next used to load config/config.yaml but can now also load config/config.php

The array in `config/config.php` in the `next` branch is the same as the one in the documentation for the latest version? http://getcockpit.com/docs#!getting_started/configuration

> I have to look into the new mongo driver thing. didn't know anything about it until now.

If you need help with the refactoring please let me know :)

**Comment by aheinze** [comment]
Hi,

yes should be the same array config. According to new MongoDB driver: I'm happy about any PR ;-)

**Comment by andrefreitas** [comment]
Hi,
I have been working in fixing this the simplest way, so I downgraded the PHP version from 7 to 5.6. 

In the next branch I am having problems. It is only loading from config/config.yml:

    Warning: file_put_contents(/var/www/html/config/config.yaml)

Do I need to make an extra step/config to read from the config/config.php ?

**Comment by aheinze** [comment]
Hi,

why the PHP downgrade? Cockpit should work fine with PHP 7.  
the config folder doesn't exist by default. You need create the config folder+ create a config.php file manually. 

the content of the file should look like this:

```
<?php

// config array
return [
   
];
```

hope this helps.

**Comment by andrefreitas** [comment]
Hi,
I downgraded the PHP version to 5.6 since the MongoDB legacy driver isn't supported in PHP 7.

I created the config folder with the file config.php inside. Can you refer the source files that load the configs from this file?

**Comment by aheinze** [comment]
Ah now I understand the downgrade.

config loading: https://github.com/aheinze/cockpit/blob/next/bootstrap.php#L52-L60

**Comment by andrefreitas** [comment]
Hi @aheinze ,
I was in a commit of next branch that only loads config.yml. I did a pull and then the bootstrap.php was updated with config.php support.

I have just made the Docker image configurable with env variables. Please update the Readme in Dockerhub: https://github.com/aheinze/cockpit-docker/blob/master/DOCKERHUB.md

Regards,
AF

**Comment by aheinze** [comment]
Done! Thanks!!
